name: Test application

on:
  push:
    branches:
      - main

jobs:
  test-application:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "18"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy config from sample
        run: cp .env.sample .env

      - name: Install dependencies
        run: npm install

      - name: Run all Node.js tests
        run: npm run test
